version: '3'
services:
  postgres:
    restart: always
    container_name: sample_db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
    - ./sql:/docker-entrypoint-initdb.d

  web:
    build:
     context: .
     dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
    expose:
      - 8080
    ports:
      - 8080:8080
