CREATE TABLE public.unit
(
    unitid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    unitname text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT unit_pkey PRIMARY KEY (unitid)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    salesid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    salestime timestamp without time zone NOT NULL,
    salestag integer NOT NULL,
    exbarbody text COLLATE pg_catalog."default",
    packname text COLLATE pg_catalog."default",
    unitname text COLLATE pg_catalog."default",
    price double precision NOT NULL,
    bonusprice double precision,
    quantity double precision,
    CONSTRAINT sales_pkey PRIMARY KEY (salesid)
);

CREATE TABLE IF NOT EXISTS public.pack
(
    packid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    unitid integer NOT NULL,
    packname text COLLATE pg_catalog."default" NOT NULL,
    packquant integer NOT NULL,
    packtype integer NOT NULL,
    CONSTRAINT pack_pkey PRIMARY KEY (packid),
    CONSTRAINT pack_unitid_fkey FOREIGN KEY (unitid)
        REFERENCES public.unit (unitid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.packprc
(
    packid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    packprice integer NOT NULL,
    packbonus integer NOT NULL,
    CONSTRAINT packprc_pkey PRIMARY KEY (packid),
    CONSTRAINT packprc_packid_fkey FOREIGN KEY (packid)
        REFERENCES public.pack (packid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.exbarc
(
    exbarcid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    packid integer NOT NULL,
    exbarbody text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT exbarc_pkey PRIMARY KEY (exbarcid),
    CONSTRAINT exbarc_packid_fkey FOREIGN KEY (packid)
        REFERENCES public.pack (packid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS public.users
(
    userid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    firstname text COLLATE pg_catalog."default",
    lastname text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (userid)
);

INSERT INTO unit (unitName)
VALUES ('kg'),
       ('шт');




INSERT INTO pack (packId, unitid, packName, packQuant, packType)
VALUES (1, 1, 'Яблоки', 1000, 1),
       (2, 2, 'Вода Бонаква', 1, 0);

INSERT INTO packprc (packid,packPrice, packBonus)
VALUES (1,120, 20),
       (2,130, 10);

INSERT INTO exbarc (exbarcid, packId,exbarBody)
VALUES (1,1,'123123'),
       (2,2,'321321');

INSERT INTO sales (salestime, salestag, exbarbody, packname, unitname, price, bonusprice, quantity)
VALUES ('2023-09-15 14:30:00',3,null,null,null,0,0,null),
       ('2023-09-15 14:30:00',2,null,null,null,0,0,null),
       ('2023-09-15 14:30:00',1,null,null,null,0,0,null);

INSERT INTO users (firstname, lastname, email, password)
VALUES ('Alex','Cuper','oskar@mail.ru','$2a$10$tsMhV35.ySspXaXaJIaVw.1lgf56PexBUTdKD3D86biNFHkVKxKOS');
-- Пароль = 1234